[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod = "168h"

[".config/fish/functions/fisher.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/jorgebucaran/fisher/refs/heads/main/functions/fisher.fish"
  refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

[".anyenv"]
  type = "git-repo"
  url = "https://github.com/anyenv/anyenv.git"
  refreshPeriod = "168h"

[".anyenv/plugins/anyenv-update"]
  type = "git-repo"
  url = "https://github.com/znz/anyenv-update.git"
  refreshPeriod = "168h"

